@startuml

start

:Declare 3 integers for example: num, one, zero;
:get input from user and store it in num;
:Set the value for one and zero as '0'
         i.e. one = 0 and zero = 0;
:Now print the Binary value for the number entered by user
 so that we can verify the number of 1's and 0's in terminal;
while (While num is greater than 0) is (yes)
    if (if the present bit of num is a set\n            i.e. num & 1 == 1) then (yes)
    :increment variable one
                 i.e one++;
    else (no)
    :increment variable zero
                 i.e. zero++;
    endif
:right shift the present bit by 1
                i.e. num >> 1;
endwhile (no)
:When the while loop condition is false
     Print the values of one and zero;

stop

@enduml




/'
repeat :While num>0;
    if (num & 1 == 1) then (yes)
    :one++;
    else (no)
    :zero++;
    endif
repeat while (num>>1)
-[hidden]->
break;

:While num<=0;
:Print one and zero;

stop

@enduml
