@startuml

start

:Declare 3 variables to store one input and two output;
:Get input from user and store it in input variable;
:Initialize the number of ones and zeroes as '0' in other two output variables.;
:Now display the Binary value for the number entered by user
 so that user can verify the number of 1's and 0's in terminal;
while (when input number is greater than 0) is (yes)
    if (is the present bit of input number a set\n            i.e. input number & 1 == 1) then (yes)
    :increment the variable for 1;
    else (no)
    :increment variable for 0;
    endif
:right shift the present bit of input number by 1;
endwhile (no)
:Dsiplay the number of 1's and 0's;

stop

@enduml




/'
repeat :While num>0;
    if (num & 1 == 1) then (yes)
    :one++;
    else (no)
    :zero++;
    endif
repeat while (num>>1)
-[hidden]->
break;

:While num<=0;
:Print one and zero;

stop

@enduml
